### ISSUE TITLE
Add tellico 3.x

### ISSUE THREAD

**Issue by gitdevmod** [RJVB/macstrop#18]
Hi,
Could you add tellico based on kf5 ? I do not know if all dependencies are already in tree. Last version on Macports is old and does work anymore with discogs database (handshake issue, maybe tls is not well supported with kdelibs4 ?)
http://tellico-project.org/

Thanks in advance !

**Comment by RJVB** [comment]
MacPorts portfiles are TCL, so there's a difference. And as such the only online test build platform I know of is for the official ports, no idea how you'd leverage that for a personal ports repository. I see the official macports-ports repository has a travis file but I have some doubts it will be easy to get it to work. There's an implicit assumption behind my macstrop tree that it will be added to an existing MacPorts install that has already been bootstrapped to some extent.

**Comment by gitdevmod** [comment]
@RJVB could you review https://github.com/gitdevmod/macstrop/blob/master/kf5/kf5-tellico/Portfile ?
It builds correctly, application running not tested
I created https://github.com/gitdevmod/macstrop/blob/master/kf5/kf5-libkcddb/Porfile but it does not build because of "Undefined symbols for architecture x86_64"

**Comment by RJVB** [comment]
Can you remind me next week please if I seem to forget? I won't get to it this week.

**Comment by gitdevmod** [comment]
@RJVB any chance to review kf5-tellico ?

**Comment by RJVB** [comment]
oops, no I've been away and busy with other stuff.

I've had some time to upgrade my port:kf5-libkcddb. I had the same missing symbol issue, which appears to be a visibility issue due to using an older clang version. It goes away when I configure with `configure.compiler=macports-clang-5.0`. I've done some compiler blacklisting in the port, but I'd need to know what compiler you use in order to get it right.
It'd be especially interesting to know if even a (very) recent Apple clang compiler fails here; that would indicate a bug in the extra-cmake-modules, I think.

**Comment by gitdevmod** [comment]
@RJVB I use this:
`$ clang -v
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`
