### ISSUE TITLE
default port group files not found after applying hierarchial patch

### ISSUE THREAD

**Issue by jjstickel** [RJVB/macstrop#24]
I tried following the instructions to resolve the port group issue. After applying the patch `patch-hierarchical-portgroup-search.diff` as instructed into `/opt/local/libexec/macports/lib`, none of the port group files in my default port tree could be found by port. Reversing the patch resolved the problem. I would like to use this more elegant approach than manually copying the port group files into the default tree.

**Comment by RJVB** [comment]
That's annoying because evidently the patch works for me. I'd need to know what you have in your $prefix/etc/macports/sources.conf, and then see log ouput from a failing port command.

There isn't really any other option between applying this patch and copying the PortGroup files manually, I'm afraid.

**Comment by jjstickel** [comment]
Applying the patch:
```
$ pwd
/opt/local/libexec/macports/lib
$ sudo patch -p2 -i /Users/Shared/install/macports/dev_fork/macstrop/sysutils/MacPorts/files/patch-hierarchical-portgroup-search.diff
patching file macports1.0/macports.tcl
Hunk #1 succeeded at 788 (offset -80 lines).
Hunk #2 succeeded at 1429 (offset -83 lines).
Hunk #3 succeeded at 1767 (offset -83 lines).
patching file port1.0/portutil.tcl
Hunk #1 succeeded at 2521 (offset -48 lines).
```
Contents of `/opt/local/etc/macports/sources.conf` (not showing most of the commented lines):
```
file:///Users/Shared/install/macports/ports
# RJVB/macstrop repo
#file:///Users/Shared/install/macports/dev_fork/macstrop [own_portgroups_first]
rsync://rsync.macports.org/macports/release/tarballs/ports.tar [default]
```
And here is a port command:
```
$ port info py36-mayavi
Warning: PortGroup python 1.0 could not be located. python-1.0.tcl does not exist.
Warning: PortGroup active_variants 1.1 could not be located. active_variants-1.1.tcl does not exist.
Warning: PortGroup github 1.0 could not be located. github-1.0.tcl does not exist.
Error: Unable to open port: invalid command name "github.setup"
```

**Comment by jjstickel** [comment]
Hmm, same behavior as shown above, no extra info about trees checked, etc. I pulled your latest master and checked that the patch I am applying, `patch-hierarchical-portgroup-search.diff`, is the same as shown in github.

**Comment by RJVB** [comment]
what if you do

```
> port -vd info foo
```

**Comment by RJVB** [comment]
Ahhh, of course. My patch made the algorithm look ONLY in local port trees defined with file:// ... which is all I have.
I've added the original single-line lookup as a fallback if all previous lookups failed, that should find any PGs not found otherwise.

The drawback is that this makes the lookup no longer perfectly hierarchical; a file:// tree listed after the standard rsync:// entry will probably override the PGs from that standard tree. We'll see if that ever leads to issues.

**Comment by jjstickel** [comment]
Thanks, this seems to be working now. I've run into another problem, but I will email you as I am not sure it's a bug or user error.
