### ISSUE TITLE
Konsole - Control key does not work

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#30]
Konsole is very difficult to use without this key. I tried switching some settings but nothing has worked.

**Comment by RJVB** [comment]
Sadly there's very little I can do about it, I'v never been able to figure out exacly why this issue occurs. It works fine when you install the qt5-kde(-devel)-x11 port and then run konsole5-x11 .

However, you should have a "Default (Mac)" keyboard profile. I'm not certain if this profile is selected by default when you run konsole for the first time: check under Settings/Edit Current Profile/Keyboard. I created this profile to circumvent the problem, and it works for me.

Konsole5-x11 a great terminal emulator for X11; in "native" mode I'm less convinced if Konsole is really a better alternative than Terminal.app or iTerm.

**Comment by Tatsh** [comment]
For the novelty I might figure out this issue and send a patch upstream. It's not critical to me right now as I'm using iTerm and I agree; I don't see Konsole as a viable alternative right now on macOS.

**Comment by RJVB** [comment]
(Replying via email)

The control key works, it is the usual Ctrl+XX combinations that stopped working somewhere during the transition from Qt4 to Qt5. I'm not certain that the issue is in Konsole.

I'm including a Mac-specific keymap which should solve the issue; does it NOT do that for anyone (or are their combinations you are missing)?
