### ISSUE TITLE
quassel-client: Qt fatal error on exit

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#39]
<img width="420" alt="Qt fatal error-2019-03-12 16-11-28" src="https://user-images.githubusercontent.com/724848/54232754-d1d15c80-44e1-11e9-8637-b1c783a0d43f.png">

Every time I exit Quassel client I get this error. Clicking Exit is impossible as the app will hang. Clicking Abort works.

The log shows the same error:

```
 $ /Applications/MacPorts/Quassel\ Client.app/Contents/MacOS/Quassel\ Client
2019-03-12 16:12:35 [Warn ] Icon theme "oxygen" not found.
2019-03-12 16:12:35 [Warn ] Missing icon: "message-quassel-tray" (using fallback: "message")
2019-03-12 16:12:40 [Info ] Quitting...
2019-03-12 16:12:40 [Info ] Client shutting down...
Trying to access a singleton that has not been instantiated yet
```

The app works completely otherwise.

**Comment by RJVB** [comment]
>Trying to access a singleton that has not been instantiated yet

This is actually a bug in quassel; it installs a log message handler but doesn't uninstall it after the above-mentioned singleton has been deleted. Any debug/warning/whatever output generated by Qt, Qt plugins or KF5 code will then trigger the abort. And since that abort will call into the same mechanism you get a stack recursion until the application is killed by the kernel.

This is one of the glitches I mentioned before; a fix is pending.

**Comment by RJVB** [comment]
Fix pushed.

I forgot the rev-bump, would you mind doing `sudo port -n upgrade --force quassel [+variants]` ?

**Comment by Tatsh** [comment]
One problem and I forgot to mention this earlier:

```
Error: Unable to open port: invalid command name "langselect_qm_dir"
```

Needs `PortGroup       locale_select 1.0`

**Comment by Tatsh** [comment]
Otherwise, it works.
