### ISSUE TITLE
librsvg fails to build

### ISSUE THREAD

**Issue by Tatsh** [RJVB/macstrop#74]
[main.log](https://github.com/RJVB/macstrop/files/3883116/librsvg-main.log.gz)

**Comment by RJVB** [comment]
What do you know about Rust?

```
:info:build    --> /opt/local/var/macports/build/_Users_tatsh_dev_macports-all_macstrop_graphics_librsvg/librsvg/work/librsvg-2.42.2/rust/vendor/cssparser/src/parser.rs:572:17
:info:build     |
:info:build 547 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
:info:build     |                                                   - let's call the lifetime of this reference `'1`
:info:build ...
:info:build 560 |             Some(ref cached_token)
:info:build     |                  ---------------- borrow of `self.input.cached_token` occurs here
:info:build ...
:info:build 572 |                 self.input.cached_token = Some(CachedToken {
:info:build     |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
:info:build ...
:info:build 584 |         Ok(token)
:info:build     |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`
:info:build error: aborting due to previous error
:info:build For more information about this error, try `rustc --explain E0506`.
:info:build error: Could not compile `cssparser`.
```

In this case I'm blocked on an older librsvg version because of the fact I install Cairo with the infinality patches and I haven't yet found the time (nor urgency) to update all that to newer versions. Can I assume that you do not use those patches? The improve font rendering quality to beyond that of CoreText (to my eyes), but that gain is largely limited to X11 (even if qt5-kde can be told to use FontConfig for font rendering).

I'll make some time later today to hack port:cairo and port:librsvg so they install newer versions when not using the infinality patches. Or see if I can just upgrade cairo+infinality.

**Comment by RJVB** [comment]
I've upgraded port:cairo and could thus remove my librsvg clone. The port should thus build for you now (or if not, you'd have to report it on trac).
