### ISSUE TITLE
kf5-konsole not found

### ISSUE THREAD

**Issue by 21stcaveman** [RJVB/macstrop#94]
Trying to install kf5-konsole, and I get a 'port not found' error.

**Comment by RJVB** [comment]
On Thursday January 05 2023 21:11:41 Hamid wrote:
>Trying to install kf5-konsole, and I get a 'port not found' error.

I had the same thing, and then did

```
> touch `port dir kf5-kauth`/../konsole5/Portfile
> portindex
```

and the port was found again. I know what this implies but not how it could have happened on both our systems (if it fixes the issue for you too)...

**Comment by 21stcaveman** [comment]
That did fix the issue indeed.
A bit confused here, that Portfile already was there and had appropriate permissions and all. What did we just do to fix the issue?!

**Comment by RJVB** [comment]
On Friday January 06 2023 09:24:47 Hamid wrote:
>That did fix the issue indeed.
>A bit confused here, that Portfile already was there and had appropriate permissions and all. What did we just do to fix the issue?!

Make `portindex` detect the file as new. That's why I said that I could understand that the file's mod time had somehow been changed (moved back in time) on 1 (my) system but not how it could be the case on both our systems. Git usually does not bother with file times or permissions.

(I know I need to get back to the qt5-kde issue ... swamped)

**Comment by 21stcaveman** [comment]
huh... weird. Thanks, glad you had a workaround for it, appreciate it.
