### ISSUE TITLE
dbusmenu-qt5

### ISSUE THREAD

**Issue by 21stcaveman** [RJVB/macstrop#95]
Trying to install dbusmenu-qt5, I'm getting:
```
dbusmenu-qt5: PortGroup LTO 1.0 could not be located. LTO-1.0.tcl does not exist
```

I have confirmed, LTO-1.0.tcl does exist in /opt/local/site-ports/_resources/port1.0/group/
what am I missing here?

**Comment by RJVB** [comment]
>I have confirmed, LTO-1.0.tcl does exist in /opt/local/site-ports/_resources/port1.0/group/

When you do a `ls -l /opt/local/site-ports/_resources/port1.0/group/` you do indeed see the file show up in capital letters? Does the logfile show any additional output that could help understand what's wrong here?

The installation instructions for my ports tree have an optional section describing how to patch the "base" install so that PortGroup files are taken from the same tree as the port requesting them, if possible. Did you apply that patch? Not that it ought to be necessary here, because that particular one gets included through my Qt5 PortGroup and that file is found, clearly.

I had a quick look at the PortGroup procedure in the current "base" sources; it does not appear to do any name-checking itself.

**Comment by 21stcaveman** [comment]
following the patch process fixed it:
```
%> (cd /opt/local/libexec/macports/lib ;
sudo patch -p2 -i /opt/local/site-ports/sysutils/MacPorts/files/patch-hierarchical-portgroup-search.diff)
```

I don't quite understand why it was necessary post upgrade (I upgraded to mac 13.5 and reinstalled macports) as I have not done this patch in the original install. But hey, as long as it works! 
Thanks.

**Comment by RJVB** [comment]
>I don't quite understand why it was necessary post upgrade (I upgraded to mac 13.5 and reinstalled macports) as I have not done this patch in the original install. But hey, as long as it works! 
>Thanks.

I also don't understand; I'll have to check if the PortGroup search algorithm was changed. It used to be that it would find the file in the first tree where it existed, so it would always find a candidate IF one was present...
